apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- rbac.yaml
- https://github.com/argoproj/argo-events/manifests/base
- event-bus.yaml
namespace: argo-events

